name: Remove Experimental Packages

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  deploy:
    uses: ronin-co/github-actions/.github/workflows/remove-experimental.yml@main
    secrets: inherit
